import type { Channel, Post } from "@/types";

export const DEFAULT_CHANNELS: Channel[] = [
  { id: "telegram", title: "Telegram", username: "telegram", lastPostAt: Date.now() / 1000 - 3600 },
  { id: "durov", title: "Durov's Channel", username: "durov", lastPostAt: Date.now() / 1000 - 86400 },
  { id: "tondev", title: "TON Dev", username: "tondev", lastPostAt: Date.now() / 1000 - 7200 },
];

function ts(offsetSeconds: number) {
  return Math.floor(Date.now() / 1000) - offsetSeconds;
}

export const DEFAULT_POSTS: Post[] = [
  {
    id: "p1",
    channelId: "telegram",
    channelTitle: "Telegram",
    channelUsername: "telegram",
    text: "Telegram 10.0 is out — new stickers, improved voice and video calls, and more. Update on App Store and Google Play.",
    date: ts(1800),
    views: 12500,
    likes: 342,
    comments: [],
  },
  {
    id: "p2",
    channelId: "tondev",
    channelTitle: "TON Dev",
    channelUsername: "tondev",
    text: "TON Connect 2.0 — a single way to connect wallets across all dApps. Documentation has been updated.",
    date: ts(7200),
    views: 8900,
    likes: 201,
    comments: [],
  },
  {
    id: "p3",
    channelId: "telegram",
    channelTitle: "Telegram",
    channelUsername: "telegram",
    text: "Fragment has launched username auctions. You can now get short, memorable usernames for your account.",
    date: ts(10800),
    views: 45000,
    likes: 1200,
    comments: [],
  },
  {
    id: "p4",
    channelId: "durov",
    channelTitle: "Durov's Channel",
    channelUsername: "durov",
    text: "Free speech is the foundation of progress. Platforms must protect people's right to express their opinions.",
    date: ts(86400),
    views: 200000,
    likes: 15000,
    comments: [],
  },
  {
    id: "p5",
    channelId: "tondev",
    channelTitle: "TON Dev",
    channelUsername: "tondev",
    text: "Jetton standard (JRC-2) — create tokens on TON. Check the repo for examples and tutorials.",
    date: ts(90000),
    views: 5600,
    likes: 89,
    comments: [],
  },
  {
    id: "p6",
    channelId: "telegram",
    channelTitle: "Telegram",
    channelUsername: "telegram",
    text: "Bot API 7.9: new features for developers. Support for media up to 4 GB for Premium bots.",
    date: ts(172800),
    views: 32000,
    likes: 890,
    comments: [],
  },
  {
    id: "p7",
    channelId: "durov",
    channelTitle: "Durov's Channel",
    channelUsername: "durov",
    text: "Privacy is not a feature, it's a fundamental human right. We build Telegram with that in mind.",
    date: ts(259200),
    views: 350000,
    likes: 28000,
    comments: [],
  },
  {
    id: "p8",
    channelId: "tondev",
    channelTitle: "TON Dev",
    channelUsername: "tondev",
    text: "TON DNS: human-readable names for wallets and smart contracts. No more copying long addresses.",
    date: ts(345600),
    views: 15000,
    likes: 456,
    comments: [],
  },
];
